title:            Brad Peters
description:      My website.
canonical: https://www.bpeters.id.au

# Owner/author information
owner:
  name:           Brad Peters
  avatar:         bradp.jpg
  bio:            " "
  email:          website@bpeters.id.au
  github:         ubersejanus     
  disqus:         bradpeters
  location:       "Melbourne, AU"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_AU

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog
  - title: Map
    url: /map
    external: false
  - title: Achievements
    url: /achievements
    external: false
  - title: Media
    url: /media

# Links for social media buttons
social:
  - title: "facebook-official"
    url: "https://www.facebook.com/brad.j.peters"
  - title: "instagram"
    url: "https://www.instagram.com/fun_brad"
  - title: "twitter"
    url: "https://www.twitter.com/ubersejanus"
  - title: "flickr"
    url: "https://www.flickr.com/photos/ubersejanus/albums"
  - title: "youtube-play"
    url: "https://www.youtube.com/channel/UCyMViNv6JQeE5yqT3WYuoDQ/videos"    
  - title: "snapchat"
    url: "https://www.snapchat.com/add/ubersejanus"
  - title: "steam"
    url: "https://steamcommunity.com/id/ubersejanus"
  - title: "rss"
    url: "/feed.xml"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Victoria
future:      true
highlighter: rouge
markdown:    kramdown

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:	/:categories/:year-:month/:title

excerpt_separator: <!--more-->

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", vendor]

