title:            Brad Peters
description:      My website.
canonical: http://www.bpeters.id.au

# Owner/author information
owner:
  name:           Brad Peters
  avatar:         avatar.png
  bio:            " "
  email:          website@bpeters.id.au
  twitter:        ubersejanus
  github:         ubersejanus
  instagram:      ubjersejanus
  dribbble:       
  disqus:         bradpeters
  location:       "Melbourne, AU"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_AU

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog
  - title: Map
    url: /map
    external: false
  - title: Achievements
    url: /achievements
    external: false
  - title: Media
    url: /media

# Links for social media buttons
social:
  - title: "facebook"
    url: "https://www.facebook.com/brad.j.peters"
  - title: "twitter"
    url: "https://www.twitter.com/ubersejanus"
  - title: "flickr"
    url: "https://www.flickr.com/photos/ubersejanus/albums"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCyMViNv6JQeE5yqT3WYuoDQ/videos"    
  - title: "snapchat"
    url: "https://www.snapchat.com/add/ubersejanus"    
  - title: "instagram"
    url: "https://www.instagram.com/ubersejanus"
  - title: "rss"
    url: "/feed.xml"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Victoria
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:	/:categories/:year-:month/:title

excerpt_separator: <!--more-->

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

